### ISSUE TITLE
No progress indicator - program stuck?

### ISSUE THREAD

**Issue by Pajamaman** [tsasioglu/Total-Uninstaller#5] opened 2015-04-14 17:53 UTC
I didn't explicitly choose to run the program as administrator, but when it launched I did select "Yes" at the UAC prompt. Now it's just sitting here:

![image](https://cloud.githubusercontent.com/assets/1323271/7143419/c9789af4-e29c-11e4-811d-be7e23928721.png)

Do I need to right click > run as administrator, or is it just taking a really long time? There's no way to tell.

**Comment by tsasioglu** [comment] 2015-04-14 18:33
No you don't need to right click -> run as admin.

I suspect it's launched the registered uninstall program, but if it has no gui you won't see anything until it's finished. Check your task manager.

**Comment by Pajamaman** [comment] 2015-04-14 19:01
Well, it sat like that for about an hour. I cancelled and tried again selecting just a few things, and I think something else may be going on:

![image](https://cloud.githubusercontent.com/assets/1323271/7144960/282d75d4-e2a6-11e4-9405-d4ee5059630b.png)

I don't see anything in task manager that looks like an uninstaller.

Edit: also, cancel doesn't seem to be working:

![image](https://cloud.githubusercontent.com/assets/1323271/7145098/fe95b9ba-e2a6-11e4-9578-d229fce9a078.png)

I don't think I'm just being impatient - it's been about 5 minutes since I hit cancel.

One other thing: even though it said earlier it was uninstalling program 2/3 (like it had completed one), all three programs are still listed as being installed.

**Comment by tsasioglu** [comment] 2015-04-14 19:19
The cancel (currently) only cancels after the running uninstall is finished. 

Are there any recent .log files in your temp folder (%TEMP%)? That's where visual studio uninstallers like to spew out their logs.

**Comment by tsasioglu** [comment] 2015-04-15 18:59
Did you get to the bottom of this?

**Comment by Pajamaman** [comment] 2015-04-16 19:11
No. It's still doing the same thing. I cleaned out my %TEMP% and nothing is showing up in there when I try to uninstall those advertising SDKs.

Edit: when I try to uninstall just this one program the count in the lower left gets all screwy

![image](https://cloud.githubusercontent.com/assets/1323271/7189363/a8db9f94-e43b-11e4-83ff-d51861b8ab04.png)

Same thing happens with the other two when I try to uninstall them individually.

Edit 2: I was able to uninstall everything with the command line exe from Konstantin.

**Comment by Trass3r** [comment] 2015-04-17 20:11
Same for me on x64 Win7 SP1 :(

**Comment by tsasioglu** [comment] 2015-04-17 20:23
Was it the same advertising SDK you had problems with Trass3r?
I'll try and get it installed and see if I can reproduce it.

**Comment by Trass3r** [comment] 2015-04-17 20:28
No I already had that uninstalled via the cmdline tool before.
I selected other packages like App Insights and AzureTools.
And it also hang with uninstalling item 2. Waiting on something, i.e. no cpu load.

**Comment by tsasioglu** [comment] 2015-04-18 06:58
I've added some logging (output to %appdata%/totaluninstaller), which will pinpoint exactly where it got stuck and hopefully give us a clue what the issue is...

**Comment by kamakazikamikaze** [comment] 2015-04-30 22:20
I also got stuck at waiting for something to happen after loading the program, selecting products, and pressing "Uninstall selected items."

I had to right click -> run as admin for it to work.
Also, because I ran it on a work computer under a managed domain, I also had to select "Unblock" in the properties window.

Ran quickly, efficiently, and with no issues after that.

**Comment by tsasioglu** [comment] 2015-07-09 22:08
Closing as this hasn't been seen in a while. The fairies must have fixed it.

**Closed as completed by tsasioglu** 2015-07-09 22:08 UTC
Labels: bug
